### ISSUE TITLE
No static call

### ISSUE THREAD

**Issue by RubenWalraevens** [ichtus/exceptions#2]
Please avoid using static calls as they aren't as elegant.

https://github.com/ichtus/exceptions/blob/master/src/Dispatchers/Dispatcher.php#L38

**Comment by mallinus** [comment]
+1.

Possible fix: setContainer helper function inside the trait

**Comment by dealloc** [comment]
This is to prevent a hard dependency on laravel/framework (which provides the app helper) and bypasses the usage of a setter (like done [here](https://github.com/ichtus/commands/blob/master/src/Dispatcher.php#L69)) as they aren't as elegant. I find this the most suited solution

**Comment by mallinus** [comment]
@dealloc setter function would be more elegant than a static call.
